version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '5173:80'
    container_name: ecommerce_cart_challenge_frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
